[build]
builder = "nixpacks"

[deploy]
restartPolicyType = "always"

[[services]]
name = "web"
source = "backend"

[services.variables]
PORT = "8000"
ENVIRONMENT = "production"

[services.healthcheck]
path = "/health"
timeout = 300

[services.deploy]
replicas = 1
strategy = "rolling"

[[services]]
name = "beat"
source = "backend"

[services.variables]
ENVIRONMENT = "production"

[services.deploy]
replicas = 1
strategy = "rolling"
startCommand = "celery -A app.celery_app beat --loglevel=info"

[[services]]
name = "worker"
source = "backend"

[services.variables]
ENVIRONMENT = "production"

[services.deploy]
replicas = 1
strategy = "rolling"
startCommand = "celery -A app.celery_app worker --loglevel=info"
