[build]
builder = "dockerfile"
dockerfilePath = "railway.dockerfile"

[deploy]
startCommand = "./start.sh"
healthcheckPath = "/health"
healthcheckTimeout = 300
preDeployCommand = "alembic upgrade head"
restartPolicyType = "on_failure"

[env]
FORCE_DEPLOY = "$(date +%s)"
CACHE_BUST = "1754202844"
