[build]
builder = "dockerfile"
dockerfilePath = "railway.dockerfile"

[deploy]
startCommand = "./start.sh"
healthcheckPath = "/health"
healthcheckTimeout = 300
preDeployCommand = "alembic upgrade head"
restartPolicyType = "on_failure"

[env]
# Railway will automatically set PORT
# All other environment variables should be set in Railway dashboard
