services:
- type: web
  name: ttpro-api
  env: docker
  autoDeploy: true
  healthCheckPath: /
  preDeployCommand: alembic upgrade head
- type: worker
  name: ttpro-celery
  env: docker
- type: worker
  name: ttpro-celery-beat
  env: docker
databases:
- name: titletesterpro-db
  databaseName: titletesterpro
  user: ttprouser
  plan: free
