services:
  - type: web
    name: ttpro-api
    env: docker
    autoDeploy: true
    healthCheckPath: /
  - type: worker
    name: ttpro-celery
    env: docker
    autoDeploy: true
    startCommand: celery -A app.robust_tasks worker --loglevel=info
  - type: worker
    name: ttpro-celery-beat
    env: docker
    autoDeploy: true
    startCommand: celery -A app.robust_tasks beat --loglevel=info --pidfile=

databases:
  - name: titletesterpro-db
    databaseName: titletesterpro
    user: ttprouser
    plan: free