"""add stripe fields

Revision ID: add_stripe_fields_20250808
Revises: add_billing_fields
Create Date: 2025-08-08 12:45:00.000000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'add_stripe_fields_20250808'
down_revision = 'add_billing_fields'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('stripe_subscription_id', sa.String(), nullable=True))
    op.add_column('users', sa.Column('subscription_updated_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'subscription_updated_at')
    op.drop_column('users', 'stripe_subscription_id')
    # ### end Alembic commands ###