"""add stripe fields

Revision ID: add_stripe_fields_20250808
Revises: add_billing_fields
Create Date: 2025-08-08 12:45:00.000000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'add_stripe_fields_20250808'
down_revision = '3e7a8467480a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('stripe_subscription_id', sa.String(), nullable=True))
    op.add_column('users', sa.Column('subscription_updated_at', sa.DateTime(), nullable=True))
    
    # Ensure all required Stripe fields exist
    # Note: stripe_customer_id, subscription_status, subscription_plan, subscription_period_end 
    # should already exist from previous migrations, but adding them if not present
    
    # Check if columns exist first to avoid errors
    connection = op.get_bind()
    inspector = sa.inspect(connection)
    columns = [col['name'] for col in inspector.get_columns('users')]
    
    if 'stripe_customer_id' not in columns:
        op.add_column('users', sa.Column('stripe_customer_id', sa.String(), nullable=True))
    if 'subscription_status' not in columns:
        op.add_column('users', sa.Column('subscription_status', sa.String(), nullable=False, server_default='free'))
    if 'subscription_plan' not in columns:
        op.add_column('users', sa.Column('subscription_plan', sa.String(), nullable=False, server_default='free'))
    if 'subscription_period_end' not in columns:
        op.add_column('users', sa.Column('subscription_period_end', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'subscription_updated_at')
    op.drop_column('users', 'stripe_subscription_id')
    
    # Note: Not dropping other Stripe fields as they may be used elsewhere
    # ### end Alembic commands ###