"""add billing fields to users

Revision ID: billing_fields_001
Revises: 7fad97faccae
Create Date: 2025-01-31 00:00:00.000000

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'billing_fields_001'
down_revision: Union[str, None] = '7fad97faccae'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('stripe_customer_id', sa.String(), nullable=True))
    op.add_column('users', sa.Column('subscription_status', sa.String(), nullable=True, server_default='free'))
    op.add_column('users', sa.Column('subscription_plan', sa.String(), nullable=True, server_default='free'))
    op.add_column('users', sa.Column('subscription_period_end', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'subscription_period_end')
    op.drop_column('users', 'subscription_plan')
    op.drop_column('users', 'subscription_status')
    op.drop_column('users', 'stripe_customer_id')
    # ### end Alembic commands ###