"""Update ABTest schema - rename youtube_video_id to video_id and original_title to video_title

Revision ID: 7fad97faccae
Revises: a103396d4ac3
Create Date: 2025-07-16 23:34:31.604548

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7fad97faccae'
down_revision: Union[str, Sequence[str], None] = 'a103396d4ac3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ab_tests', sa.Column('video_id', sa.String(), nullable=False))
    op.add_column('ab_tests', sa.Column('video_title', sa.String(), nullable=False))
    op.drop_column('ab_tests', 'youtube_video_id')
    op.drop_column('ab_tests', 'original_title')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ab_tests', sa.Column('original_title', sa.VARCHAR(), nullable=False))
    op.add_column('ab_tests', sa.Column('youtube_video_id', sa.VARCHAR(), nullable=False))
    op.drop_column('ab_tests', 'video_title')
    op.drop_column('ab_tests', 'video_id')
    # ### end Alembic commands ###
