#!/bin/bash
# TTPROv5 Backend Configuration Script
# This script provides the exact environment variable configuration for the new Render backend

set -euo pipefail

echo "🚀 TTPROv5 BACKEND CONFIGURATION GUIDE"
echo "======================================"
echo ""

echo "📋 RENDER ENVIRONMENT VARIABLES TO SET:"
echo "========================================"
echo ""
echo "# Core Application"
echo "ENVIRONMENT=production"
echo "LOG_LEVEL=info"
echo "APP_NAME=titletesterpro"
echo ""
echo "# Database & Redis (Internal URLs from screenshots)"
echo "DATABASE_URL=postgresql://postgres_ttprov5_user:VE1ODbnInDCjcThgm4UVqWBNKU6GYK1n@dpg-d2cb900gjohc73fv7h60-a.virginia-postgres.render.com/postgres_ttprov5"
echo "REDIS_URL=redis://red-d2cbelf5iees73fgg71g:6379"
echo ""
echo "# Firebase Admin (Secret File Only)"
echo "GOOGLE_APPLICATION_CREDENTIALS=/etc/secrets/firebase-key.json"
echo "ALLOW_ENV_FALLBACK=0"
echo "FIREBASE_DEBUG=1  # Temporarily for verification, then set to 0"
echo ""
echo "# Google OAuth (Backend Web Client)"
echo "GOOGLE_CLIENT_ID=***REPLACE_WITH_YOUR_CLIENT_ID***"
echo "GOOGLE_CLIENT_SECRET=***REPLACE_WITH_YOUR_CLIENT_SECRET***"
echo "GOOGLE_API_KEY=***REPLACE_WITH_YOUR_API_KEY***"
echo ""
echo "# JWT Secret"
echo "JWT_SECRET_KEY=***REPLACE_WITH_YOUR_JWT_SECRET***"
echo ""
echo "# CORS Origins (comma-separated, no spaces)"
echo "CORS_ORIGINS=https://www.titletesterpro.com,https://titletesterpro.com,https://*.vercel.app,http://localhost:5173"
echo ""
echo "# Optional Stripe (if needed)"
echo "# STRIPE_SECRET_KEY=sk_test_..."
echo "# STRIPE_PUBLISHABLE_KEY=pk_test_..."
echo ""
echo "🔐 SECRET FILE TO ADD:"
echo "====================="
echo "Path: firebase-key.json"
echo "Content: Complete Firebase service account JSON from your Firebase console"
echo ""
echo "📋 DEPLOYMENT STEPS:"
echo "===================="
echo "1. Go to Render Dashboard → Your new TTPROv5 backend service"
echo "2. Settings → Environment Variables → Add all variables above"
echo "3. Settings → Secret Files → Add firebase-key.json with Firebase service account"
echo "4. Deploy → Connect repository → Branch: fix/ttprov5-backend-redeploy-20250810_121500"
echo "5. Wait for deployment to complete"
echo "6. Note the new backend URL (https://your-service.onrender.com)"
echo ""
echo "🧪 VERIFICATION:"
echo "================"
echo "After deployment, test these endpoints:"
echo "curl https://YOUR_BACKEND_URL/healthz  # Should return {\"ok\": true}"
echo "curl https://YOUR_BACKEND_URL/health   # Should return {\"status\": \"healthy\"}"
echo "curl https://YOUR_BACKEND_URL/debug/firebase  # Should return Firebase config details"
echo ""
echo "Then update FIREBASE_DEBUG=0 and redeploy for production lockdown."
echo ""
echo "✅ READY FOR DEPLOYMENT!"