name: backend
on:
  push: { branches: [main, bootstrap/v5] }
  pull_request:
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with: { python-version: '3.11' }
      - run: pip install -r requirements.txt || true
      - run: echo "no backend tests yet" || true
YML < /dev/null